site_name: 開放科技車庫 | Open Tech Garage
site_url: https://otg.ocf.tw/ # Placeholder, user might need to change this
site_description: "開放科技車庫（Open Tech Garage）是一個聚焦於評估、分析與測試多種開源軟體工具的專案"
site_author: "財團法人開放文化基金會 (Open Culture Foundation, OCF)"
copyright: "CC-BY 4.0 姓名標示"
nav:
  - 首頁: index.md
  - 情境故事: story.md
  - 工具評估方法:
      - 簡介: assessment/index.md
      - Scoring: assessment/scoring.md
      - Data Structure: assessment/data-structure.md
      - Example Assessment: assessment/example-assessment.md
      - Tool Template: assessment/TOOL_TEMPLATE.md
  - 工具清單（依類別）: categories/
  - 工具清單（依名稱）: tool_list_name.md
  - 如何貢獻: CONTRIBUTING.md
theme:
  name: material
  icon:
    logo: material/security # Placeholder, might need a different icon
  favicon: asserts/security.svg # Placeholder, might need a different favicon
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 自動偵測模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: '#6450DC' # OCF Purple
      accent: '#0091DA' # OCF Cyan
      toggle:
        icon: material/weather-sunny
        name: 切換到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: '#6450DC' # OCF Purple
      accent: '#CE0058' # OCF Magenta
      toggle:
        icon: material/weather-night
        name: 切換到明亮模式
  language: zh-TW
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - content.tooltips
  custom_dir: overrides # This assumes 'overrides' directory will be copied or created
plugins:
  - search:
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
      lang:
        - en
        - zh
  - offline
  - privacy
  - social:
      cards_layout_options:
        font_family: Noto Sans TC
  - git-revision-date-localized:
      locale: en
      timezone: Asia/Taipei
      fallback_to_build_date: true
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      base_path: [assessment]
      auto_append:
        - includes/abbreviations.md # This assumes 'includes' directory will be copied or created
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tabbed:
      alternate_style: true
extra:
  analytics:
    provider: google
    property: G-X3DG2E5E3W # Placeholder, user might need to change this
  social:
    - icon: material/home
      link: https://otg.ocf.tw/ # Placeholder, user might need to change this
    - icon: fontawesome/brands/github
      link: https://github.com/ocftw/otg # Placeholder, user might need to change this
    
extra_css:
  - stylesheets/extra.css # This assumes 'stylesheets' directory will be copied or created